Added Landing page
Nagashree01/berry-store-ecom pull request #1
Opened 2022-04-09 14:07 UTC by Nagashree01

- added navigation bar
- added banner
- added featured categories section
- added footer section

![Homepage1](https://user-images.githubusercontent.com/57230665/162577715-6d19a971-a7d6-49e4-86ba-38ce246c1d40.jpg)
![homepage2](https://user-images.githubusercontent.com/57230665/162577722-d6590adb-c7a1-4f6e-a3bb-a5e65206aee8.jpg)

2022-04-09 16:17 UTC, JantuDeb approved these changes
This looks good to me

2022-04-09 16:17 UTC, JantuDeb commented on src/components/categories/category.jsx
> +      const response = await axios.get("/api/categories");
You can destructure `data` here

2022-04-09 17:34 UTC, Nagashree01 commented on src/components/categories/category.jsx
> +      const response = await axios.get("/api/categories");
yes will do this. Thank you!

2022-04-09 17:38 UTC, Kothalkarpriya requested changes
Do look into my comments and implement them as you go

2022-04-09 17:38 UTC, Kothalkarpriya commented on src/components/categories/category.jsx
> +      console.log(err);
It's good you used Try can catch here

2022-04-09 17:38 UTC, Kothalkarpriya commented on src/components/shared/footer/footer.jsx
> +    )
Do use code formatter at last, it will manage the syntax. You missed the semicolon here to close the return ().

2022-04-09 17:38 UTC, Kothalkarpriya commented on src/components/shared/navbar/navbar.jsx
> +                <Link className="text-style-none text-size-m btn link-btn" to="/" >Login</Link>
If you have used Routes then use /Login to navigate

2022-04-09 17:38 UTC, Kothalkarpriya commented on src/pages/Home/homepage.jsx
> +//import NavBar from "../../components/shared/navbar/navbar";
Remove commented code if not in use

2022-04-09 17:38 UTC, Kothalkarpriya commented on src/pages/Home/homepage.jsx
> +              src="../assets/banner.png"
you can import images at the start and use them inside {//imageName}. It will help you to reuse them as necessary

2022-04-10 04:50 UTC, Nagashree01 commented on src/components/shared/footer/footer.jsx
> +    )
yes will use from now

2022-04-10 04:50 UTC, Nagashree01 commented on src/pages/Home/homepage.jsx
> +//import NavBar from "../../components/shared/navbar/navbar";
yes will remove them

2022-04-10 04:51 UTC, Nagashree01 commented on src/pages/Home/homepage.jsx
> +              src="../assets/banner.png"
yes will do this

2022-04-10 06:50 UTC, merged